# Generated by Django 3.0.7 on 2020-06-28 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0004_auto_20200627_1750'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splitsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.date.today)),
                ('factor', models.IntegerField()),
                ('omgekeerde_splitsing', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producten.Product')),
            ],
        ),
    ]
