# Generated by Django 3.0.7 on 2020-06-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacties', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correctie',
        ),
    ]
