# Generated by Django 3.0.7 on 2020-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0002_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dividend',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
