# Generated by Django 3.0.7 on 2020-06-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0003_product_dividend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dividend',
            new_name='met_dividend',
        ),
    ]
